Artifact.create(name: "Famicom Soundfont", description: "", tag_list: ['soundfont', 'videogame'], software_list: ['linuxsampler', 'carla', 'fluidsynth', 'timidity'], mirrors: ['http://www.woolyss.com/chipmusic/chipmusic-soundfonts/Famicom.zip'], file: File.open('sf2/Famicom.zip') , author: 'Kitt', license_id: 9, file_format: 'sf2', more_info_urls: ['http://www.k3.dion.ne.jp/~kitt/sf/lib.html', 'http://www.woolyss.com/chipmusic-soundfonts.php'])

Artifact.create(name: "F-Zero Soundfont", description: "", tag_list: ['soundfont', 'videogame'], software_list: ['linuxsampler', 'carla', 'fluidsynth', 'timidity'], mirrors: ['http://www.woolyss.com/chipmusic/chipmusic-soundfonts/F-Zero.zip'], file: File.open('sf2/F-Zero.zip') , author: 'Blitz Lunar', license_id: 9, file_format: 'sf2', file_format: 'sf2', more_info_urls: ['http://web.archive.org/web/20110111173805/http://www.shakal.net/lunar/misc/soundfonts/', 'http://www.woolyss.com/chipmusic-soundfonts.php'])

Artifact.create(name: "GBFont Soundfont", description: "", tag_list: ['soundfont', 'videogame'], software_list: ['linuxsampler', 'carla', 'fluidsynth', 'timidity'], mirrors: ['http://www.woolyss.com/chipmusic/chipmusic-soundfonts/GBFont.zip'], file: File.open('sf2/GBFont.zip') , author: 'MaliceX', license_id: 9, file_format: 'sf2', more_info_urls: ['http://web.archive.org/web/20100518201945/http://djtbmx.soulbreakers.com/junkpile', 'http://www.woolyss.com/chipmusic-soundfonts.php'])

Artifact.create(name: "GXSCC gm 033 Soundfont", description: "", tag_list: ['soundfont', 'videogame'], software_list: ['linuxsampler', 'carla', 'fluidsynth', 'timidity'], mirrors: ['http://www.woolyss.com/chipmusic/chipmusic-soundfonts/GXSCC_gm_033.zip'], file: File.open('sf2/GXSCC_gm_033.zip') , author: 'Zandro', license_id: 9, file_format: 'sf2', more_info_urls: ['http://zandro.freeunixhost.com/', 'http://www.woolyss.com/chipmusic-soundfonts.php'])

Artifact.create(name: "Kirby's Dream Land 3 Soundfont", description: "", tag_list: ['soundfont', 'videogame'], software_list: ['linuxsampler', 'carla', 'fluidsynth', 'timidity'], mirrors: ["http://www.woolyss.com/chipmusic/chipmusic-soundfonts/Kirby's_Dream_Land_3.zip"], file: File.open("sf2/Kirby's_Dream_Land_3.zip") , author: 'Blitz Lunar', license_id: 9, file_format: 'sf2', more_info_urls: ['http://web.archive.org/web/20110111173805/http://www.shakal.net/lunar/misc/soundfonts/', 'http://www.woolyss.com/chipmusic-soundfonts.php'])

Artifact.create(name: "Mega Man X Soundfont", description: "", tag_list: ['soundfont', 'videogame'], software_list: ['linuxsampler', 'carla', 'fluidsynth', 'timidity'], mirrors: ['http://www.woolyss.com/chipmusic/chipmusic-soundfonts/Mega_Man_X.zip'], file: File.open('sf2/Mega_Man_X.zip') , author: 'Blitzlunar', license_id: 9, file_format: 'sf2', more_info_urls: ['http://web.archive.org/web/20110111173805/http://www.shakal.net/lunar/misc/soundfonts/', 'http://www.woolyss.com/chipmusic-soundfonts.php'])

Artifact.create(name: "MP NES Composer Soundfont", description: "", tag_list: ['soundfont', 'videogame'], software_list: ['linuxsampler', 'carla', 'fluidsynth', 'timidity'], mirrors: ['http://www.woolyss.com/chipmusic/chipmusic-soundfonts/MP_NES_Composer.zip'], file: File.open('sf2/MP_NES_Composer.zip') , author: 'Awpwr', license_id: 9, file_format: 'sf2', more_info_urls: ['http://www.youtube.com/user/AWPWR#p/u/1/1nl6zL3rm2Y', 'http://www.woolyss.com/chipmusic-soundfonts.php'])

Artifact.create(name: "Mystical Ninja Starring Goemon Soundfont", description: "", tag_list: ['soundfont', 'videogame'], software_list: ['linuxsampler', 'carla', 'fluidsynth', 'timidity'], mirrors: ['http://www.woolyss.com/chipmusic/chipmusic-soundfonts/Mystical_Ninja_Starring_Goemon.zip'], file: File.open('sf2/Mystical_Ninja_Starring_Goemon.zip') , author: 'Blitz Lunar', license_id: 9, file_format: 'sf2', more_info_urls: ['http://web.archive.org/web/20110111173805/http://www.shakal.net/lunar/misc/soundfonts/', 'http://www.woolyss.com/chipmusic-soundfonts.php'])

Artifact.create(name: "Nokia 30 Soundfont", description: "", tag_list: ['soundfont', 'videogame'], software_list: ['linuxsampler', 'carla', 'fluidsynth', 'timidity'], mirrors: ['http://www.woolyss.com/chipmusic/chipmusic-soundfonts/Nokia_30.zip'], file: File.open('sf2/Nokia_30.zip') , author: 'Bryan Bilocura', license_id: 9, file_format: 'sf2', more_info_urls: ['http://discussion.forum.nokia.com/forum/showthread.php?t=34181', 'http://www.woolyss.com/chipmusic-soundfonts.php'])

Artifact.create(name: "OPL-3 FM 128M Soundfont", description: "", tag_list: ['soundfont', 'videogame'], software_list: ['linuxsampler', 'carla', 'fluidsynth', 'timidity'], mirrors: ['http://www.woolyss.com/chipmusic/chipmusic-soundfonts/OPL-3_FM_128M.zip'], file: File.open('sf2/OPL-3_FM_128M.zip') , author: 'Zandro', license_id: 9, file_format: 'sf2', more_info_urls: ['http://zandro.freeunixhost.com/', 'http://www.woolyss.com/chipmusic-soundfonts.php'])

Artifact.create(name: "Secret of Mana Soundfont", description: "", tag_list: ['soundfont', 'videogame'], software_list: ['linuxsampler', 'carla', 'fluidsynth', 'timidity'], mirrors: ['http://www.woolyss.com/chipmusic/chipmusic-soundfonts/Secret_of_Mana.zip'], file: File.open('sf2/Secret_of_Mana.zip') , author: 'Blitz Lunar', license_id: 9, file_format: 'sf2', more_info_urls: ['http://web.archive.org/web/20110111173805/http://www.shakal.net/lunar/misc/soundfonts/', 'http://www.woolyss.com/chipmusic-soundfonts.php'])

Artifact.create(name: "Setzer's SPC Soundfont Soundfont", description: "", tag_list: ['soundfont', 'videogame'], software_list: ['linuxsampler', 'carla', 'fluidsynth', 'timidity'], mirrors: ["http://www.woolyss.com/chipmusic/chipmusic-soundfonts/Setzer's_SPC_Soundfont.zip"], file: File.open("sf2/Setzer's_SPC_Soundfont.zip") , author: 'Setzer', license_id: 9, file_format: 'sf2', more_info_urls: ['http://soundfonts.darkesword.com/', 'http://www.woolyss.com/chipmusic-soundfonts.php'])

Artifact.create(name: "Square Soundfont", description: "", tag_list: ['soundfont', 'videogame'], software_list: ['linuxsampler', 'carla', 'fluidsynth', 'timidity'], mirrors: ['http://www.woolyss.com/chipmusic/chipmusic-soundfonts/Square.zip'], file: File.open('sf2/Square.zip') , author: 'Steven Rhodes', license_id: 9, file_format: 'sf2', more_info_urls: ['http://setu.castleparadox.com/sf2/', 'http://www.woolyss.com/chipmusic-soundfonts.php'])

Artifact.create(name: "Super Bomberman Soundfont", description: "", tag_list: ['soundfont', 'videogame'], software_list: ['linuxsampler', 'carla', 'fluidsynth', 'timidity'], mirrors: ['http://www.woolyss.com/chipmusic/chipmusic-soundfonts/Super_Bomberman.zip'], file: File.open('sf2/Super_Bomberman.zip') , author: 'Blitz Lunar', license_id: 9, file_format: 'sf2', more_info_urls: ['http://web.archive.org/web/20110111173805/http://www.shakal.net/lunar/misc/soundfonts/', 'http://www.woolyss.com/chipmusic-soundfonts.php'])

Artifact.create(name: "Super Mario Kart Soundfont", description: "", tag_list: ['soundfont', 'videogame'], software_list: ['linuxsampler', 'carla', 'fluidsynth', 'timidity'], mirrors: ['http://www.woolyss.com/chipmusic/chipmusic-soundfonts/Super_Mario_Kart.zip'], file: File.open('sf2/Super_Mario_Kart.zip') , author: 'Blitz Lunar', license_id: 9, file_format: 'sf2', more_info_urls: ['http://web.archive.org/web/20110111173805/http://www.shakal.net/lunar/misc/soundfonts/', 'http://www.woolyss.com/chipmusic-soundfonts.php'])

Artifact.create(name: "Super Mario World Soundfont", description: "", tag_list: ['soundfont', 'videogame'], software_list: ['linuxsampler', 'carla', 'fluidsynth', 'timidity'], mirrors: ['http://www.woolyss.com/chipmusic/chipmusic-soundfonts/Super_Mario_World.zip'], file: File.open('sf2/Super_Mario_World.zip') , author: 'Blitz Lunar', license_id: 9, file_format: 'sf2', more_info_urls: ['http://web.archive.org/web/20110111173805/http://www.shakal.net/lunar/misc/soundfonts/', 'http://www.woolyss.com/chipmusic-soundfonts.php'])

Artifact.create(name: "Tales of Phantasia Soundfont", description: "", tag_list: ['soundfont', 'videogame'], software_list: ['linuxsampler', 'carla', 'fluidsynth', 'timidity'], mirrors: ['https://www.dropbox.com/s/sb8vbedb51i1e4o/SNES_Sakuraba_V5.sf2', 'http://www.woolyss.com/chipmusic/chipmusic-soundfonts/Tales_of_Phantasia.zip'], file: File.open('sf2/Tales_of_Phantasia.zip') , author: 'Christian Esquivel', license_id: 9, file_format: 'sf2', more_info_urls: ['http://www.woolyss.com/chipmusic-soundfonts.php'])

Artifact.create(name: "The Nes Soundfont Soundfont", description: "", tag_list: ['soundfont', 'videogame'], software_list: ['linuxsampler', 'carla', 'fluidsynth', 'timidity'], mirrors: ['http://www.woolyss.com/chipmusic/chipmusic-soundfonts/The_Nes_Soundfont.zip'], file: File.open('sf2/The_Nes_Soundfont.zip') , author: 'TheEightBit', license_id: 9, file_format: 'sf2', more_info_urls: ['http://www.woolyss.com/chipmusic-soundfonts.php'])

Artifact.create(name: "The Ultimate Megadrive Soundfont Soundfont", description: "", tag_list: ['soundfont', 'videogame'], software_list: ['linuxsampler', 'carla', 'fluidsynth', 'timidity'], mirrors: ['http://www.woolyss.com/chipmusic/chipmusic-soundfonts/The_Ultimate_Megadrive_Soundfont.zip'], file: File.open('sf2/The_Ultimate_Megadrive_Soundfont.zip') , author: 'TheEightBit', license_id: 9, file_format: 'sf2', more_info_urls: ['http://www.woolyss.com/chipmusic-soundfonts.php'])

Artifact.create(name: "Zelda 3 Soundfont", description: "", tag_list: ['soundfont', 'videogame'], software_list: ['linuxsampler', 'carla', 'fluidsynth', 'timidity'], mirrors: ['http://www.woolyss.com/chipmusic/chipmusic-soundfonts/Zelda_3.zip'], file: File.open('sf2/Zelda_3.zip') , author: 'Blitz Lunar', license_id: 9, file_format: 'sf2', more_info_urls: ['http://web.archive.org/web/20110111173805/http://www.shakal.net/lunar/misc/soundfonts/', 'http://www.woolyss.com/chipmusic-soundfonts.php'])